### ISSUE TITLE
Setting to stop the navigation when at the bottom/top of the page

### ISSUE THREAD

**Issue by postkevone** [MaxGyver83/tw5-keyboard-navigation#2]
Hello,

I've recently discovered this plugin and since then my experience with tiddlywiki has changed in better.
Everythings works fine but when I have a lot of tiddlers opened I sometimes press the button too many times and end up navigating to the opposite of the page (top/bottom).
It would be great if there was an option to stop once you have reached the last tiddler available in a direction, instead of being redirected to the opposite of the page.
Let me know what you think.

Cheers.

**Comment by MaxGyver83** [comment]
Hello!

Your suggestion sounds good to me! I'm going to add an option for that. Probably next week.

Best regards,
Max

**Comment by MaxGyver83** [comment]
The new option is available. Please try version 0.5.0: https://www.maximilian-schillinger.de/tw5-keyboard-navigation-plugin.html
