### ISSUE TITLE
Considering dealing with keys in `onkeydown`

### ISSUE THREAD

**Issue by onlyice** [MaxGyver83/tw5-keyboard-navigation#6]
In current version, when I intent to copy some text, it cound accidently close a tiddler. The key press sequences is (generated by [Keyboard Event Viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html)):

![image](https://user-images.githubusercontent.com/1173899/147807627-efcfa74f-275a-47b9-9508-3109cb276b66.png)

When I copy come text, it could be either <kbd>Meta</kbd> or <kbd>C</kbd> key released at last. I think you can handling these events in `onkeydown` instead of `onkeyup`, which can test modifiers more accurately.

(sorry for bad english)

**Comment by MaxGyver83** [comment]
Oh, that's bad. It never happened to me but when I try (`Ctrl-c`, releasing `Ctrl` first), I can reproduce it.

Your idea sounds good. I'll test it with triggering on key down events.

**Comment by MaxGyver83** [comment]
Fixed in commit a307167aba2d3993220fa9f7c33859410c4bbd9c.

Check the [demo page](http://maximilian-schillinger.de/tw5-keyboard-navigation-plugin.html) for **version 0.7.1**.

**Comment by onlyice** [comment]
Cool, thanks!
