### ISSUE TITLE
Newly opened tiddlers from search do not always receive focus

### ISSUE THREAD

**Issue by michaeljmcd** [MaxGyver83/tw5-keyboard-navigation#7]
This behavior seems to be a bit inconsistent, but this seems to be the simplest case I've been able to find:

1. Open the wiki at <https://maximilian-schillinger.de/tw5-keyboard-navigation-plugin.html>
2. Close all tiddlers.
3. Open advanced search from the tools tab.
4. On the filter tab, use `[[Hello TiddlyWiki users!]]`
5. Click on the single search result once.

The result looks like this:

<img width="1691" alt="Screenshot 2023-09-19 at 9 43 52 AM" src="https://github.com/MaxGyver83/tw5-keyboard-navigation/assets/972214/c32f3513-5c16-44a9-bccc-ce1367e63a48">

Interestingly, if you click the search result link a second time, it will receive focus.

It's probably not the biggest deal, but I notice it more with very long search results.

**Comment by MaxGyver83** [comment]
Interesting! I can reproduce this. I'll need to investigate.

**Comment by MaxGyver83** [comment]
Fixed in version 0.7.3! Could you try again?

**Comment by michaeljmcd** [comment]
I installed 0.7.3 over the weekend and have been using it a bit since then. I haven't run into the issue since updating. Thanks!

**Comment by MaxGyver83** [comment]
Thank you for testing!
